### ISSUE TITLE
Zentrums-Mitarbeiter:in arbeitet Hilfesuchenden Liste ab um Hilfesuchende mit Freiwilligen zu verbinden

### ISSUE THREAD

**Issue by moejoe** [moejoe/hilfswerk#1]
# Hintergrund
Der/die Mitarbeiter:in (MA) arbeitet in einem der Hilfswerk-Standorte.
Anfragen von Hilfesuchenden sind immer einem Standort zugewiesen.

Die Aufgabe wird von unterschiedlichen MAs an mehreren Standorten durchgeführt,
sobald er/sie Zeit dafür hat. (Über den ganzen Tag verteilt)

# Design

https://sketch.cloud/s/YLJ9v/p/user-story-a-issue-1

# Ablauf

**Nebenbedingung**:

Es soll vermieden werden, dass 2 Mitarbeiter:innen an demselben Hilfesuchenden arbeiten.

## Main Flow

1. MA hat eine Liste mit `Unterstützungs Anfragen`. (Excel Liste)
2. MA wählt einen Fall aus (Excel Liste)
3. MA sucht nach einem passenden Freiwilligen
4. MA telefoniert mit ausgewählten Freiwilligen und gibt alle Informationen sowie Kontaktdaten weiter. Der Freiwillige soll sich in 10 Minuten beim Hilfesuchenden melden
5. MA telefoniert mit Hilfesuchenden und kündigt den Anruf des Freiwilligen an.
6. MA vermerkt die Vermittlung

### 2. Auswahl eines Falls

Folgende informationen helfen der/dem MA einen Fall auszuwählen (in Reihenfolge der Priorität):

- Name der Person
- Tätigkeit
- Due date
- Disztanz (PLZ, Strasse wenn manuell - sonst ranking)

Um die Nebenbedingung, dass nicht 2 MAs am selben Fall arbeiten sollen zu verhindern, soll bei der Auswahl des Falles, der Fall "gesperrt" werden.
Andere Mitarbeiter sollen den Fall dann nicht abarbeiten.

### 4. Auswahl eines Freiwilligens

MA sucht jemanden, der/die nahe genug wohnt und die Tätigkeit anbietet. 
Sie hat eine Liste an potentiellen Freiwilligen, und telefoniert die durch.

### 6. Vermittlung vermerken

Folgende infos sind relevant:

- Wer hat vermittelt (MitarbeiterIn)
- Wer wurde Vermittelt (Freiwillige)
- An wen (Hilfesuchende)
- Wofür (Tätigkeit)
- Wann (jetzt)
- Freies Textfeld für weitere Informationen (wichtig)

## Alternativ Flow - kein passender Freiwilliger - Fall nicht zeitkritisch

4a. Der Fall wird zurück gelegt und später vermittelt.

## Alternativ Flow - kein passender Freiwilliger - Fall zeitkritisch

4b. MA ruft den Hilfesuchenden an, und teilt mit, dass die Aufgabe nicht erledigt werden kann.
5b. Der Fall wird auf Obsolet gestellt.

**Comment by heckmueller** [comment]
Hier findet ihr die ersten UX/UI Vorschläge. Bitte gerne auf Sketch.cloud kommentieren und ich mach zeitnah adaption und aktualisiere die Files dort: https://sketch.cloud/s/YLJ9v/p/user-story-a-issue-1
