### ISSUE TITLE
Zentrums-Mitarbeiter:in versucht Helfer:innen-Auslastung zu erfassen

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#37]
# Hintergrund

Ein Helfer kann:
- **Teilausgelastet sein** (Er/sie macht bereits Einsätze, hat aber noch freie Kapazitäten um weitere Einsätze zu übernehmen. Dementsprechend sollte er/sie weiterhin in der Liste geführt werden)
- **Vollausgelastet sein** (Er/sie soll in der Liste nicht ehr angezeigt werden. Wenn sichte Helfende Person wieder meldet und freie Ressourcen signalisiert, wird sie durch die Koordinatorinnen in der Liste wieder frei geschalten)

Derzeit gibt es keine Möglichkeit diesen Status zu erfassen oder zu verwalten.

# Ablauf

A
1. Helfer:in und Hilfesuchende:r werden gematched. 
2. Kontaktaufnahme mit Helfer:in
3. Aus dem Kontakt entsteht die Information ob eine Vollauslastung vorliegt
4. Statusänderung und damit Entfernung aus der Suchliste

### A3. Aus dem Kontakt entsteht die Information ob eine Vollauslastung vorliegt
Wenn keine Vollauslastung vorliegt, wird auch nichts verändert. Der/die Helfer:in bleibt einfach in der Liste. Das bereits eine Teilauslastung vorliegt, wird über as Auflisten der Einsätze sichtbar.

### A4. Statusänderung und damit Entfernung aus der Suchliste
Wenn der/die Helfer:in im Kontakt mit der Koordinatorin signalisiert das eine Vollauslastung vorliegt, wird dies mittels Checkbox gespeichert und der/die Helfer:in wird fortan nicht mehr in der primären Suchliste angezeigt.

B
1. Helfer:in meldet sich proaktiv und gibt an freie Ressourcen zu haben
2. Koordinatorin sucht den/die Helfer:in nach Namen
3. Koordinatorin schaltet Helfer:in wieder für die Suchliste frei

### B2. Koordinatorin sucht den/die Helfer:in nach Namen
Derzeit gibt es noch keine Möglichkeit eine:n Helfer:in (nach Namen) zu suchen, vor allem wenn die Person nicht mehr in der primären Suchliste aufscheint. Sobald es ein Suchfeld in der primären Suchliste gibt, kann der/die entsprechende Helfer:in gezielt gesucht werden.

### B3. Koordinatorin schaltet Helfer:in wieder für die Suchliste frei
Derzeit gibt es noch keine Möglichkeit eine:n Helfer:in wieder in die primäre Suchliste aufzunehmen. Sobald Helfer:innen gezielt gesucht werden können, und ihre Daten bearbeitet werden können, ist es auch möglich den Status "Vollauslastung" wieder aufzuheben.

# Offene Fragen

- Was ist die (technisch) einfachste Lösung um eine Helfer:innen Suche (nach Namen) zu ermöglichen

**Comment by heckmueller** [comment]
Combines with #39

**Comment by moejoe** [comment]
## Vorschlag

Flag beim Helfer ob "ausgelastet" oder nicht.
Ausgelastete Helfer werden auf der Matching Liste nicht angezeigt.

 Suche nach Name (Vorname / Nachname?) - in der Suchliste sollen alle Treffer aufscheinen... (um wieder freischalten zu können)

Aufwand: ein paar Stunden

TODO: 
- [ ] Ablauf abklären mit MA (Harald)
