### ISSUE TITLE
Zentrums-Mitarbeiter:in will Helfer:innen-Daten bearbeiten

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#38]
# Hintergrund

Im direkten Gespräch mit Helfer:innen können sich Änderungen von deren Daten ergeben. Vor allem Tätigkeiten und Sonstige Filter (Auto vorhanden, Freiwilliger) können sich leicht ändern.

# Ablauf

1. Die Koordinatorin erhebt im Gespräch mit dem/der Helfer:in neue Informationen
2. Sie sucht den/die Helfer:in gezielt heraus und öffnet deren Datensatz
3. Sie nimmt Änderungen an den Daten vor
4. Die Änderungen werden gespeichert

### 3. Sie nimmt Änderungen an den Daten vor
Der Datensatz kann einfach als Formular angezeigt werden, und somit können Änderungen leicht vorgenommen werden.

# Offene Fragen

- Ist es (leicht) möglich Änderungen automatisch zu speichern, oder brauchen wir User-Interaktion (Save Button) um das zu tun?

**Comment by heckmueller** [comment]
Combines with #39

**Comment by moejoe** [comment]
Alles bearbeitbar. 
Kontakt, Tätigkeiten, Sonstiges (Zivi, Risikogruppe, ...), anmerkungen und "Ausgelastet"

Aufwand: 1 Tag.

**Comment by tuwrraphael** [comment]
frontend url /helfer_innen/{id}
