### ISSUE TITLE
Zentrums-Mitarbeiter:innen scrollen sehr viel rauf und runter und verlieren den Überblick in der Suchergebnisliste

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#40]
# Hintergrund

Nach Beobachtung der Arbeitsumgebung und dem Benutzungsverhalten der User, ist es offensichtlich geworden das ein Sidebar-Pattern besser funktionieren würde.

# Design
[Sketch.cloud](http://sketch.cloud)

**Comment by moejoe** [comment]
aufwand: klein (1 Std?)
