### ISSUE TITLE
Minor Changes/Bugs/Enhancements

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#49]
- [x] **Email und Telefonnummer kein Pflichtfeld**, wenn man einen Kontakt anlegt oder ändert.
- [x] **Vollauslastung** soll by default unchecked sein
- [x] **Sortierung der Einsatzliste soll nach Datum** absteigend sein (aktuellster Einsatz oben, Ältester unten)
- [x] **Das Sonstiges Feld Freiwilliger soll "WHW FW" heissen** (um interne Verwirrung zu vermeiden)
- [x] **Einsätze bekommen ein zusätzliches Feld "Stunden"** in das nur zahlen eingetragen werden können, nicht mandatory, muss in der Liste nicht angezeigt werden.

**Comment by heckmueller** [comment]
@moejoe Frage: Werden die PLZ in der Filterliste autopopulated? Ich sehe in den Daten gerade das wir jemanden von ausserhalb Wiens in der Liste haben.

**Comment by moejoe** [comment]
> @moejoe Frage: Werden die PLZ in der Filterliste autopopulated? Ich sehe in den Daten gerade das wir jemanden von ausserhalb Wiens in der Liste haben.

in der filterliste sind bisher nur wiener PLZ drinnen.
die sind nicht datenbankabhängig erstellt sondern fix im frontend drinnen.
