### ISSUE TITLE
Minor Issues

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#54]
#### 06/04/2020 (sortiert nach Dringlichkeit)
- [ ] Die Liste der verfügbaren Helfer:innen soll nach Nachname sortiert sein.
- [x] Eigenen Branche mit Echtdaten anlegen, damit wir intern das Layout mit den korrekten Datenmengen testen können _(NICHT via Staging verfügbar)_
- [ ] Bei den Actions in der Suchliste dann den Button "Einsatz protokollieren" hinzufügen
_(wenn es einfacher ist die selbe Struktur wie in der anderen Liste zu machen, also mit ausklappen und Detaildaten, wäre das eh gut. Weil dann kann man das wieder verfügbar machen einfach im bearbeiten des/der Helfer:in machen)_
- [ ] Nach eintragen eines Einsatzes in dem Fenster bleiben 
_(nicht automatisch zurück zur Liste gehen)_
- [x] Kopfzeile mit Logout wieder zurück bringen
- [x] In die Kopfzeile einen Link "Anleitung" hinzufügen der auf eine statische Seite verweist.

**Comment by tuwrraphael** [comment]
@heckmueller bitte neues Issue zum Punkt
> Nach eintragen eines Einsatzes in dem Fenster bleiben
(nicht automatisch zurück zur Liste gehen)

anlegen mit genauerer Beschreibung was auf der Seite nach dem Eintragen erwartet wird
