### ISSUE TITLE
Zentrums-Mitarbeiter:innen müssen bei den Helfer:innen den Status DSGVO ready eintragen können

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#65]
# Hintergrund
Diese Möglichkeit muss bis Ende April bestehen, um DSVGO konform zu sein. Es muss ein Filterkriterium sein damit nach den Leuten gesucht werden kann die noch nicht erledigt sind.

**Comment by moejoe** [comment]
![image](https://user-images.githubusercontent.com/1154515/79121822-864d4a00-7d96-11ea-8bf3-81cfbeecb58c.png)
![image](https://user-images.githubusercontent.com/1154515/79121843-92d1a280-7d96-11ea-9b63-da2f973dab70.png)
