### ISSUE TITLE
Zentrums-Mitarbeiter:innen wollen nach dem bearbeiten einer Helfer:in wieder an die Stelle der Liste zurück kehren wo sie davor waren

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#67]
# User Feedback

> Bei jeder Art der Filterung – nach Bez. oder Name etc. – wenn man auf Helfer bearbeiten geht und dann abbricht …. weil man dann ev. einen Einsatz eintragen will, … dann springt die Liste komplett auf den Anfang (Helfer mit A) zurück ……    wenn man einen bestimmten Helfer einfach in der alphabetischen Gesamtliste sucht, dann kann man alles schauen, machen, abbrechen und es springt NICHT zurück, was viel praktischer ist …
…. das ist jetzt wirklich eine „Laus“ und kein Bug ;-)

# Aufwand
Wenn das wie oben beschrieben ohnehin schon geht, ist es wohl einfacher zu implementieren, ansonsten...?

**Comment by moejoe** [comment]
closed by #77
