### ISSUE TITLE
Zentrums-Mitarbeiter:innen vergessen am Freitag einen Einsatz einzutragen, bemerken das erst am Montag und können dann das korrekte Datum für den Einsatz nicht erfassen

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#69]
# User Feedback 
> Ad Einsätze wäre es super wenn man den Tag des Einsatzes eintragen könnte

# Lösungsansatz
Das Datumsfeld im Einsatzformular wieder sichtbar machen und nur mit dem aktuellen Datum vorbefüllen, jedoch editierter machen. Es braucht keinen Datumspicker, Texteingabe mit Formatüberprüfung reicht völlig.

**Comment by moejoe** [comment]
closed by #76

**Comment by moejoe** [comment]
closed by #76
