### ISSUE TITLE
Zentrums-Mitarbeiter:innen wollen Einsätze protokollieren deren Länge 1,5h ist

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#70]
# User Feedback
> Wenn man Kommazahlen bei den Stunden des Einsatzes machen könnte

Ich vermute das das Feld ein Integer ist, und wir das Problem ev. lösen können indem wir einfach Kommazahlen zulassen.

**Comment by heckmueller** [comment]
Zeit als Minuten eintragen

**Comment by moejoe** [comment]
![image](https://user-images.githubusercontent.com/1154515/79121754-54d47e80-7d96-11ea-98b0-785f774cde6f.png)
