### ISSUE TITLE
Zentrums-Mitarbeiter:innen wollen einen Einsatz bearbeiten

### ISSUE THREAD

**Issue by heckmueller** [moejoe/hilfswerk#72]
# Hintergrund

Folgende Fälle sind dazu bereits aufgetreten:
- Datum nachträglich ändern
- Stunden ändern (hat doch länger gedauert, war schneller als gedacht)
- Anmerkung machen
- Einsatz löschen (hat doch nicht statt gefunden)

# Lösungen

Wenn es eine Seite gibt um Einsätze einzusehen, könnte damit auch folgende Issues gelöst werden:
- #71 Wenn die Gesamtzahl Helfer:innen auf der Verfügbar Seite und Gesamtzahl Einsätze auf der Einsatz Seite gelistet wird, könnten sie sich auf der Einsatzseite die Stundenzahl manuell extrahieren
- #69 Wenn die Einsatzseite wie die Suchseite aussieht, und es eine Möglichkeit gibt dann auf eine Bearbeiten Seite zu gehen, könnten diverse Daten ausgebessert und nachgetragen werden
- #8 Einfaches Troubleshooting is jetzt bereits möglich (User suchen, Einsätze sehen -> typische Probleme können damit gelöst werden). Wenn es die Möglichkeit gibt den Einsatz zu bearbeiten, sind alle Fälle von Troubleshooting abgedeckt.

**Comment by moejoe** [comment]
![image](https://user-images.githubusercontent.com/1154515/79121707-37071980-7d96-11ea-9c87-7697efc327d1.png)
